### ISSUE TITLE
is.request(y) is not TRUE

### ISSUE THREAD

**Issue by bloyal** [nicolewhite/RNeo4j#32]
Just upgraded R to 3.2.1 this morning, Neo4j to 2.2.3, and RNeo4j to 1.4.1. I'm able to create a graph object (with authentication) but when I try to create a node I get this:

> alice = createNode(graph, "Person", name="Alice")
Error: is.request(y) is not TRUE

I get the same response if I try to clear(graph). Cypher create and match queries from the browser appear to work fine. Any ideas?

**Comment by nicolewhite** [comment]
Hey Brian, 

I'm not on R 3.2.1 yet. I'll update and investigate when I get a chance.

**Comment by nicolewhite** [comment]
What version of `httr` do you have? It looks like `httr` was [just recently updated from 0.6.1 to 1.0.0](https://github.com/hadley/httr/releases/tag/v1.0.0) so I'm guessing there were some breaking changes in the API. You can find out with:

```r
packageVersion("httr")
```

**Comment by nicolewhite** [comment]
Alright, I've confirmed it's due to breaking changes between httr v0.6.1 and v1.0.0. Until I can figure out what's broken, you can continue on by removing httr v1.0.0 and installing v0.6.1:

```r
remove.packages("httr")
install.packages("http://cran.r-project.org/src/contrib/Archive/httr/httr_0.6.1.tar.gz", repos=NULL, type="source")
```

**Comment by bloyal** [comment]
Works like a dream, thanks Nicole!

**Comment by nicolewhite** [comment]
Nice! I'll leave this open until I can get RNeo4j working with httr 1.0.0.

**Comment by tekfenonline** [comment]
I upgrade R 3.2.1 and fixed it.

**Comment by raquele** [comment]
I have the same problem. So, I removed 'httr' 1.0 to install previous version 0.6 but the following error appeared:


* installing *source* package 'httr' ...
** package 'httr' successfully unpacked and MD5 sums checked
** libs

*** arch - i386
Warning: execução do comando 'make -f "C:/PROGRA~1/R/R-32~1.1/etc/i386/Makeconf" -f "C:/PROGRA~1/R/R-32~1.1/share/make/winshlib.mk" SHLIB="httr.dll" OBJECTS="writer.o"' teve status 127
ERROR: compilation failed for package 'httr'
* removing 'C:/Users/anderson/Documents/R/win-library/3.2/httr'
Warning in install.packages :
  running command '"C:/PROGRA~1/R/R-32~1.1/bin/x64/R" CMD INSTALL -l "C:\Users\anderson\Documents\R\win-library\3.2" "C:/Users/anderson/AppData/Local/Temp/RtmpsbZA7t/downloaded_packages/httr_0.6.1.tar.gz"' had status 1
Warning in install.packages :
  installation of package ‘C:/Users/anderson/AppData/Local/Temp/RtmpsbZA7t/downloaded_packages/httr_0.6.1.tar.gz’ had non-zero exit status

Any idea? 
Thanks

**Comment by nicolewhite** [comment]
What version of RNeo4j are you on?

**Comment by raquele** [comment]
Hey Nicole White,

In fact, after I used the function clear(graph) the program works :-)
I'm using the last version.

Best regards,
Raquel Lopes Costa
